# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRVrs8yNGbcaZGo8qBr6O2KovlAEtVOd
"""

import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import os
import gdown
from transformers import RobertaModel, RobertaTokenizer

# ==========================================
# 1. YOUR EXACT MODEL BLUEPRINT
# ==========================================
class UltimateJobFraudClassifier(nn.Module):
    def __init__(self, vocab_size, glove_dim, lstm_hidden, num_numeric_features, num_classes):
        super(UltimateJobFraudClassifier, self).__init__()

        self.roberta = RobertaModel.from_pretrained('roberta-base')
        self.bi_lstm = nn.LSTM(input_size=glove_dim, hidden_size=lstm_hidden, batch_first=True, bidirectional=True)
        self.numeric_branch = nn.Sequential(
            nn.Linear(num_numeric_features, 16),
            nn.ReLU()
        )

        combined_dim = 768 + (lstm_hidden * 2) + 16
        self.classifier = nn.Sequential(
            nn.Linear(combined_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, roberta_ids, roberta_mask, glove_data, numeric_data):
        roberta_features = self.roberta(input_ids=roberta_ids, attention_mask=roberta_mask).pooler_output
        lstm_out, (hn, _) = self.bi_lstm(glove_data)
        glove_features = torch.cat((hn[-2, :, :], hn[-1, :, :]), dim=1)
        numeric_features = self.numeric_branch(numeric_data)
        final_combined = torch.cat((roberta_features, glove_features, numeric_features), dim=1)
        return self.classifier(final_combined)

# ==========================================
# 2. LOAD MODEL & TOKENIZER (From Google Drive)
# ==========================================
@st.cache_resource
def load_ai_model():
    """Downloads uncompressed model from Drive if missing, then loads it."""
    # Changed extension to just .pth
    MODEL_PATH = "Roberta__1_fake_job_model.pth"

    if not os.path.exists(MODEL_PATH):
        # 🚨 REPLACE THIS WITH YOUR NEW GOOGLE DRIVE FILE ID 🚨
        file_id = '1T9qk1-ThGiit3rL8beH9rh-o7L0ziwgE'
        url = f'https://drive.google.com/uc?id={file_id}'

        with st.spinner("Downloading AI Model from Cloud... (This may take a few minutes for the uncompressed file)"):
            gdown.download(url, MODEL_PATH, quiet=False)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = UltimateJobFraudClassifier(
        vocab_size=10000,
        glove_dim=100,
        lstm_hidden=64,
        num_numeric_features=2,
        num_classes=2
    ).to(device)

    # Standard PyTorch load (gzip removed)
    model.load_state_dict(torch.load(MODEL_PATH, map_location=device))

    model.eval()
    tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
    return model, tokenizer, device

model, tokenizer, device = load_ai_model()

# ==========================================
# 3. STREAMLIT USER INTERFACE
# ==========================================
st.set_page_config(page_title="Fake Job Detector", page_icon="🕵️‍♂️", layout="wide")

st.title("🕵️‍♂️ AI Fake Job Detector")
st.markdown("Enter the details of a job posting below. Our RoBERTa & Bi-LSTM hybrid model will analyze it and predict if it is **Real** or a **Scam**.")
st.divider()

col1, col2 = st.columns(2)

with col1:
    st.subheader("📝 Basic Information")
    input_title = st.text_input("Job Title", "Senior Software Engineer")
    input_department = st.text_input("Department", "Engineering")
    input_location = st.text_input("Location", "Remote")

with col2:
    st.subheader("💰 Salary & Compensation")
    input_min_salary = st.number_input("Minimum Salary ($)", min_value=0, value=50000)
    input_max_salary = st.number_input("Maximum Salary ($)", min_value=0, value=120000)
    input_benefits = st.text_input("Benefits", "Health insurance, 401k, remote work")

st.subheader("📄 Detailed Description")
input_company_profile = st.text_area("Company Profile", "We are a fast-growing tech startup...")
input_description = st.text_area("Job Description", "We are looking for an experienced Python developer...", height=150)
input_requirements = st.text_area("Requirements", "5+ years of experience in AI, PyTorch, and Streamlit...", height=100)

# ==========================================
# 4. PREDICTION LOGIC
# ==========================================
if st.button("🔍 Analyze Job Posting", use_container_width=True, type="primary"):
    with st.spinner("Neural Network is analyzing the text..."):

        # A. PREPARE ROBERTA DATA
        combined_texts = [
            input_title, input_company_profile, input_description,
            input_requirements, input_benefits, input_department, input_location
        ]

        encoded = tokenizer(
            combined_texts, padding='max_length', truncation=True,
            max_length=512, return_tensors="pt"
        )

        roberta_ids = encoded['input_ids'].view(1, -1)[:, :512].to(device)
        roberta_mask = encoded['attention_mask'].view(1, -1)[:, :512].to(device)

        # B. PREPARE GLOVE DATA
        sample_glove = [np.zeros(100) for _ in range(5)]
        glove_tensor = torch.tensor([sample_glove], dtype=torch.float32).to(device)

        # C. PREPARE NUMERIC DATA
        sample_min_scaled = (input_min_salary - 30000) / 50000
        sample_max_scaled = (input_max_salary - 50000) / 80000
        numeric_tensor = torch.tensor([[sample_min_scaled, sample_max_scaled]], dtype=torch.float32).to(device)

        # D. RUN PREDICTION
        with torch.no_grad():
            outputs = model(roberta_ids, roberta_mask, glove_tensor, numeric_tensor)
            probabilities = torch.nn.functional.softmax(outputs, dim=1)
            fake_probability = probabilities[0][1].item()

        # E. DISPLAY RESULTS
        st.divider()
        if fake_probability > 0.5:
            st.error(f"### 🚨 FAKE JOB ALERT!\n**Confidence:** {fake_probability*100:.2f}%\n\nOur AI detected suspicious patterns in this job posting. Please exercise caution.")
        else:
            st.success(f"### ✅ REAL JOB POSTING\n**Confidence:** {(1-fake_probability)*100:.2f}%\n\nThis posting appears legitimate according to our model.")